/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.tq22.battleship;

import java.io.BufferedReader;
import java.io.InputStreamReader;

/**
 * This class is the entry point and main body of the whole Battleship Game
 * program.
 */
public class App {

    private final TextPlayer player1, player2;

    /**
     * This is a constructor for an App, which will initialize the two players.
     */
    public App() {
        Board<Character> b1 = new BattleShipBoard<>(10, 20, 'X');
        Board<Character> b2 = new BattleShipBoard<>(10, 20, 'X');
        BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
        V2ShipFactory factory = new V2ShipFactory();
        player1 = new TextPlayer("A", b1, input, System.out, factory, 3, 3);
        player2 = new TextPlayer("B", b2, input, System.out, factory, 3, 3);
    }

    /**
     * This method starts placement phase for both the two players.
     */
    public void doPlacementPhase() throws IllegalArgumentException {
        player1.doPlacementPhase();
        player2.doPlacementPhase();
    }

    /**
     * This method starts attack phase for both the two players until one of the players
     * wins the game.
     */
    public void doActionPhase() {
        String result;
        int count = 1;
        while (true) {
            System.out.print("---------------------------------------------------------------------------\n"
                    + "Round " + count + ":\n");
            count++;
            result = player1.doActionPhase(player2);
            if (result != null) {
                System.out.print(result);
                break;
            }
            result = player2.doActionPhase(player1);
            if (result != null) {
                System.out.print(result);
                break;
            }
        }
    }

    public static void main(String[] args) {
        App app = new App();
        app.doPlacementPhase();
        app.doActionPhase();
    }

}
